// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_INTRO_SYN Message_MessageType = 0
	Message_INTRO_ACK Message_MessageType = 1
	Message_PING      Message_MessageType = 2
	Message_PONG      Message_MessageType = 3
	Message_ADD       Message_MessageType = 4
	Message_INTRO_BYE Message_MessageType = 5
	Message_GROUP_BYE Message_MessageType = 6
	Message_GOSSIP    Message_MessageType = 7
	Message_SUSPECT   Message_MessageType = 8
)

var Message_MessageType_name = map[int32]string{
	0: "INTRO_SYN",
	1: "INTRO_ACK",
	2: "PING",
	3: "PONG",
	4: "ADD",
	5: "INTRO_BYE",
	6: "GROUP_BYE",
	7: "GOSSIP",
	8: "SUSPECT",
}

var Message_MessageType_value = map[string]int32{
	"INTRO_SYN": 0,
	"INTRO_ACK": 1,
	"PING":      2,
	"PONG":      3,
	"ADD":       4,
	"INTRO_BYE": 5,
	"GROUP_BYE": 6,
	"GOSSIP":    7,
	"SUSPECT":   8,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0, 0}
}

type Message struct {
	Addr                 string              `protobuf:"bytes,1,opt,Name=addr,proto3" json:"addr,omitempty"`
	MessageType          Message_MessageType `protobuf:"varint,2,opt,Name=message_type,json=messageType,proto3,enum=main.Message_MessageType" json:"message_type,omitempty"`
	Details              *any.Any            `protobuf:"bytes,3,opt,Name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Message) GetMessageType() Message_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Message_INTRO_SYN
}

func (m *Message) GetDetails() *any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type ProtoMember struct {
	Addr                 string   `protobuf:"bytes,1,opt,Name=addr,proto3" json:"addr,omitempty"`
	RpcAddr              string   `protobuf:"bytes,2,opt,Name=rpcAddr,proto3" json:"rpcAddr,omitempty"`
	Incarnation          uint64   `protobuf:"varint,3,opt,Name=incarnation,proto3" json:"incarnation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoMember) Reset()         { *m = ProtoMember{} }
func (m *ProtoMember) String() string { return proto.CompactTextString(m) }
func (*ProtoMember) ProtoMessage()    {}
func (*ProtoMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *ProtoMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMember.Unmarshal(m, b)
}
func (m *ProtoMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMember.Marshal(b, m, deterministic)
}
func (m *ProtoMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMember.Merge(m, src)
}
func (m *ProtoMember) XXX_Size() int {
	return xxx_messageInfo_ProtoMember.Size(m)
}
func (m *ProtoMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMember.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMember proto.InternalMessageInfo

func (m *ProtoMember) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ProtoMember) GetRpcAddr() string {
	if m != nil {
		return m.RpcAddr
	}
	return ""
}

func (m *ProtoMember) GetIncarnation() uint64 {
	if m != nil {
		return m.Incarnation
	}
	return 0
}

type IntroducerResponse struct {
	Members              []*ProtoMember `protobuf:"bytes,1,rep,Name=members,proto3" json:"members,omitempty"`
	Incarnation          uint64         `protobuf:"varint,2,opt,Name=incarnation,proto3" json:"incarnation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *IntroducerResponse) Reset()         { *m = IntroducerResponse{} }
func (m *IntroducerResponse) String() string { return proto.CompactTextString(m) }
func (*IntroducerResponse) ProtoMessage()    {}
func (*IntroducerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *IntroducerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntroducerResponse.Unmarshal(m, b)
}
func (m *IntroducerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntroducerResponse.Marshal(b, m, deterministic)
}
func (m *IntroducerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntroducerResponse.Merge(m, src)
}
func (m *IntroducerResponse) XXX_Size() int {
	return xxx_messageInfo_IntroducerResponse.Size(m)
}
func (m *IntroducerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IntroducerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IntroducerResponse proto.InternalMessageInfo

func (m *IntroducerResponse) GetMembers() []*ProtoMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *IntroducerResponse) GetIncarnation() uint64 {
	if m != nil {
		return m.Incarnation
	}
	return 0
}

type GossipDetails struct {
	Ttl                  uint32       `protobuf:"varint,1,opt,Name=ttl,proto3" json:"ttl,omitempty"`
	B                    uint32       `protobuf:"varint,2,opt,Name=b,proto3" json:"b,omitempty"`
	T                    uint32       `protobuf:"varint,3,opt,Name=T,proto3" json:"T,omitempty"`
	Ts                   uint64       `protobuf:"varint,4,opt,Name=ts,proto3" json:"ts,omitempty"`
	Src                  *ProtoMember `protobuf:"bytes,6,opt,Name=src,proto3" json:"src,omitempty"`
	Message              *Message     `protobuf:"bytes,7,opt,Name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GossipDetails) Reset()         { *m = GossipDetails{} }
func (m *GossipDetails) String() string { return proto.CompactTextString(m) }
func (*GossipDetails) ProtoMessage()    {}
func (*GossipDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *GossipDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipDetails.Unmarshal(m, b)
}
func (m *GossipDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipDetails.Marshal(b, m, deterministic)
}
func (m *GossipDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipDetails.Merge(m, src)
}
func (m *GossipDetails) XXX_Size() int {
	return xxx_messageInfo_GossipDetails.Size(m)
}
func (m *GossipDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipDetails.DiscardUnknown(m)
}

var xxx_messageInfo_GossipDetails proto.InternalMessageInfo

func (m *GossipDetails) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *GossipDetails) GetB() uint32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *GossipDetails) GetT() uint32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *GossipDetails) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *GossipDetails) GetSrc() *ProtoMember {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *GossipDetails) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type JoinMessage struct {
	Member               *ProtoMember `protobuf:"bytes,1,opt,Name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *JoinMessage) Reset()         { *m = JoinMessage{} }
func (m *JoinMessage) String() string { return proto.CompactTextString(m) }
func (*JoinMessage) ProtoMessage()    {}
func (*JoinMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *JoinMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinMessage.Unmarshal(m, b)
}
func (m *JoinMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinMessage.Marshal(b, m, deterministic)
}
func (m *JoinMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinMessage.Merge(m, src)
}
func (m *JoinMessage) XXX_Size() int {
	return xxx_messageInfo_JoinMessage.Size(m)
}
func (m *JoinMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinMessage.DiscardUnknown(m)
}

var xxx_messageInfo_JoinMessage proto.InternalMessageInfo

func (m *JoinMessage) GetMember() *ProtoMember {
	if m != nil {
		return m.Member
	}
	return nil
}

type IntroMessage struct {
	Member               *ProtoMember `protobuf:"bytes,1,opt,Name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *IntroMessage) Reset()         { *m = IntroMessage{} }
func (m *IntroMessage) String() string { return proto.CompactTextString(m) }
func (*IntroMessage) ProtoMessage()    {}
func (*IntroMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{5}
}

func (m *IntroMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntroMessage.Unmarshal(m, b)
}
func (m *IntroMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntroMessage.Marshal(b, m, deterministic)
}
func (m *IntroMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntroMessage.Merge(m, src)
}
func (m *IntroMessage) XXX_Size() int {
	return xxx_messageInfo_IntroMessage.Size(m)
}
func (m *IntroMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IntroMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IntroMessage proto.InternalMessageInfo

func (m *IntroMessage) GetMember() *ProtoMember {
	if m != nil {
		return m.Member
	}
	return nil
}

type PingMessage struct {
	Src                  *ProtoMember `protobuf:"bytes,1,opt,Name=src,proto3" json:"src,omitempty"`
	Seq                  uint64       `protobuf:"varint,2,opt,Name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{6}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetSrc() *ProtoMember {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *PingMessage) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type PongMessage struct {
	Seq                  uint64   `protobuf:"varint,1,opt,Name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongMessage) Reset()         { *m = PongMessage{} }
func (m *PongMessage) String() string { return proto.CompactTextString(m) }
func (*PongMessage) ProtoMessage()    {}
func (*PongMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{7}
}

func (m *PongMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongMessage.Unmarshal(m, b)
}
func (m *PongMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongMessage.Marshal(b, m, deterministic)
}
func (m *PongMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongMessage.Merge(m, src)
}
func (m *PongMessage) XXX_Size() int {
	return xxx_messageInfo_PongMessage.Size(m)
}
func (m *PongMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PongMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PongMessage proto.InternalMessageInfo

func (m *PongMessage) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type SuspectMessage struct {
	Suspect              *ProtoMember `protobuf:"bytes,1,opt,Name=suspect,proto3" json:"suspect,omitempty"`
	Ts                   uint64       `protobuf:"varint,2,opt,Name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SuspectMessage) Reset()         { *m = SuspectMessage{} }
func (m *SuspectMessage) String() string { return proto.CompactTextString(m) }
func (*SuspectMessage) ProtoMessage()    {}
func (*SuspectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{8}
}

func (m *SuspectMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuspectMessage.Unmarshal(m, b)
}
func (m *SuspectMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuspectMessage.Marshal(b, m, deterministic)
}
func (m *SuspectMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuspectMessage.Merge(m, src)
}
func (m *SuspectMessage) XXX_Size() int {
	return xxx_messageInfo_SuspectMessage.Size(m)
}
func (m *SuspectMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SuspectMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SuspectMessage proto.InternalMessageInfo

func (m *SuspectMessage) GetSuspect() *ProtoMember {
	if m != nil {
		return m.Suspect
	}
	return nil
}

func (m *SuspectMessage) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func init() {
	proto.RegisterEnum("main.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterType((*Message)(nil), "main.Message")
	proto.RegisterType((*ProtoMember)(nil), "main.ProtoMember")
	proto.RegisterType((*IntroducerResponse)(nil), "main.IntroducerResponse")
	proto.RegisterType((*GossipDetails)(nil), "main.GossipDetails")
	proto.RegisterType((*JoinMessage)(nil), "main.JoinMessage")
	proto.RegisterType((*IntroMessage)(nil), "main.IntroMessage")
	proto.RegisterType((*PingMessage)(nil), "main.PingMessage")
	proto.RegisterType((*PongMessage)(nil), "main.PongMessage")
	proto.RegisterType((*SuspectMessage)(nil), "main.SuspectMessage")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x41, 0x8f, 0xd3, 0x3c,
	0x10, 0xfd, 0x9c, 0xe4, 0x6b, 0x76, 0xc7, 0x4d, 0x65, 0x2c, 0x0e, 0x59, 0x2e, 0x54, 0xe1, 0x40,
	0xd1, 0x4a, 0x59, 0xa9, 0x5c, 0x40, 0xe2, 0x52, 0xb6, 0xab, 0xaa, 0xa0, 0xb6, 0x91, 0xd3, 0x3d,
	0xec, 0x01, 0xad, 0xd2, 0xd4, 0x54, 0x91, 0x5a, 0x3b, 0xc4, 0xee, 0xa1, 0x27, 0xfe, 0x00, 0xff,
	0x80, 0x3f, 0x8b, 0xe2, 0xc4, 0x6a, 0x81, 0xc2, 0x81, 0x53, 0x66, 0xc6, 0x6f, 0x66, 0xde, 0x7b,
	0x76, 0x00, 0x6f, 0x2a, 0xb9, 0x2f, 0xe3, 0xb2, 0x92, 0x5a, 0x52, 0x6f, 0x97, 0x15, 0xe2, 0xd9,
	0xd5, 0x46, 0xca, 0xcd, 0x96, 0xdf, 0x98, 0xda, 0x6a, 0xff, 0xf9, 0x26, 0x13, 0x87, 0x06, 0x10,
	0x7d, 0x73, 0xc0, 0x9f, 0x71, 0xa5, 0xb2, 0x0d, 0xa7, 0x14, 0xbc, 0x6c, 0xbd, 0xae, 0x42, 0xd4,
	0x47, 0x83, 0x4b, 0x66, 0x62, 0xfa, 0x0e, 0xba, 0xbb, 0xe6, 0xf8, 0x51, 0x1f, 0x4a, 0x1e, 0x3a,
	0x7d, 0x34, 0xe8, 0x0d, 0xaf, 0xe2, 0x7a, 0x6e, 0xdc, 0x36, 0xda, 0xef, 0xf2, 0x50, 0x72, 0x86,
	0x77, 0xc7, 0x84, 0xc6, 0xe0, 0xaf, 0xb9, 0xce, 0x8a, 0xad, 0x0a, 0xdd, 0x3e, 0x1a, 0xe0, 0xe1,
	0xd3, 0xb8, 0xa1, 0x12, 0x5b, 0x2a, 0xf1, 0x48, 0x1c, 0x98, 0x05, 0x45, 0x5f, 0x01, 0x9f, 0xcc,
	0xa2, 0x01, 0x5c, 0x4e, 0xe7, 0x4b, 0xb6, 0x78, 0x4c, 0x1f, 0xe6, 0xe4, 0xbf, 0x63, 0x3a, 0xba,
	0xfd, 0x48, 0x10, 0xbd, 0x00, 0x2f, 0x99, 0xce, 0x27, 0xc4, 0x31, 0xd1, 0x62, 0x3e, 0x21, 0x2e,
	0xf5, 0xc1, 0x1d, 0x8d, 0xc7, 0xc4, 0x3b, 0x62, 0xdf, 0x3f, 0xdc, 0x91, 0xff, 0xeb, 0x74, 0xc2,
	0x16, 0xf7, 0x89, 0x49, 0x3b, 0x14, 0xa0, 0x33, 0x59, 0xa4, 0xe9, 0x34, 0x21, 0x3e, 0xc5, 0xe0,
	0xa7, 0xf7, 0x69, 0x72, 0x77, 0xbb, 0x24, 0x17, 0xd1, 0x27, 0xc0, 0x49, 0xcd, 0x6c, 0xc6, 0x77,
	0x2b, 0x5e, 0x9d, 0x75, 0x24, 0x04, 0xbf, 0x2a, 0xf3, 0x51, 0x5d, 0x76, 0x4c, 0xd9, 0xa6, 0xb4,
	0x0f, 0xb8, 0x10, 0x79, 0x56, 0x89, 0x4c, 0x17, 0x52, 0x18, 0xc5, 0x1e, 0x3b, 0x2d, 0x45, 0x39,
	0xd0, 0xa9, 0xd0, 0x95, 0x5c, 0xef, 0x73, 0x5e, 0x31, 0xae, 0x4a, 0x29, 0x14, 0xa7, 0xd7, 0xe0,
	0xef, 0xcc, 0x3e, 0x15, 0xa2, 0xbe, 0x3b, 0xc0, 0xc3, 0x27, 0x8d, 0xbd, 0x27, 0x4c, 0x98, 0x45,
	0xfc, 0xba, 0xc4, 0xf9, 0x7d, 0xc9, 0x77, 0x04, 0xc1, 0x44, 0x2a, 0x55, 0x94, 0xe3, 0xc6, 0x56,
	0x4a, 0xc0, 0xd5, 0x7a, 0x6b, 0x54, 0x04, 0xac, 0x0e, 0x69, 0x17, 0xd0, 0xca, 0xf4, 0x06, 0x0c,
	0xad, 0xea, 0x6c, 0x69, 0xe8, 0x06, 0x0c, 0x2d, 0x69, 0x0f, 0x1c, 0xad, 0x42, 0xcf, 0x0c, 0x76,
	0xb4, 0xa2, 0x2f, 0xc0, 0x55, 0x55, 0x1e, 0x76, 0xcc, 0x05, 0x9e, 0xa1, 0x56, 0x9f, 0xd2, 0x97,
	0xb5, 0x06, 0x73, 0x73, 0xa1, 0x6f, 0x80, 0xc1, 0x4f, 0x4f, 0x84, 0xd9, 0xd3, 0xe8, 0x0d, 0xe0,
	0x0f, 0xb2, 0x10, 0xf6, 0xcd, 0xbd, 0x82, 0x4e, 0xa3, 0xcc, 0xb0, 0x3b, 0x3b, 0xbf, 0x05, 0x44,
	0x6f, 0xa1, 0x6b, 0xcc, 0xfb, 0x87, 0xd6, 0x31, 0xe0, 0xa4, 0x10, 0x1b, 0xdb, 0xd9, 0x2a, 0x42,
	0x7f, 0x55, 0x44, 0xc0, 0x55, 0xfc, 0x4b, 0x6b, 0x70, 0x1d, 0x46, 0xcf, 0x01, 0x27, 0xf2, 0x38,
	0xa5, 0x05, 0xa0, 0x23, 0x60, 0x06, 0xbd, 0x74, 0xaf, 0x4a, 0x9e, 0x6b, 0x8b, 0xb9, 0x06, 0x5f,
	0x35, 0x95, 0x3f, 0x6f, 0xb3, 0x88, 0xd6, 0x78, 0xc7, 0x1a, 0xbf, 0xea, 0x98, 0x9f, 0xe4, 0xf5,
	0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x22, 0xf8, 0xf8, 0xd2, 0x03, 0x00, 0x00,
}
